name: nebula
description: "Music Player Build With Flutter"


publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  http: ^1.0.0 
  dartz: ^0.10.1
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  equatable: ^2.0.5
  salomon_bottom_bar: ^3.3.2
  cached_network_image: ^3.3.0
  on_audio_query: ^2.9.0
  just_audio: ^0.9.36
  path_provider: ^2.1.1
  dio: ^5.3.3
  permission_handler: ^11.0.0
  audiotagger: ^2.2.1
  marquee: ^2.2.3
  flutter_isolate: ^2.0.4
  rxdart: ^0.27.7
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  freezed_annotation: ^2.2.0
  sqflite: ^2.3.0
  carousel_slider: ^4.2.1
  device_info_plus: ^9.1.0
  dart_des: ^1.0.2
  shimmer: ^3.0.0
  youtube_explode_dart: ^2.0.0
  metadata_god: ^0.5.2+1
  bloc_concurrency: ^0.2.3
  just_audio_background: ^0.0.1-beta.13
  url_launcher: ^6.2.4
  flip_card: ^0.7.0
  flutter_local_notifications: ^17.0.0
  youtube_player_iframe: ^5.1.1
  jiosaavn: ^0.1.0
  app_links: ^4.0.1
  shared_preferences: ^2.2.2
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  spotify: ^0.13.5
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.3
  build_runner: ^2.3.3


flutter:

  uses-material-design: true


  assets:
     - assets/
